### ISSUE TITLE
⚡ Standardization of rep

### ISSUE THREAD

**Issue by luxonauta** [dracula/kurozora#1]
Hi 👋🏻 @Kiritokatklian, we need to adjust a few things first to move forward, ok? ✨

We need a separate `.md` with installation instructions to show the theme on the site.

I ask for these changes to standardize with the other repositories [see an example](https://github.com/dracula/notepad-plus-plus); this is also important because it helps other potential users who would like to contribute too! 😁

Let me know if something isn't possible or if you have any questions! 🙂

**Comment by kiritokatklian** [comment]
Thanks @luxonauta! I moved the installation steps to `INSTALL.md`. I also updated `README` to be similar to the one in the example.

Let me know if further changes are required 😄

**Comment by luxonauta** [comment]
Excellent!💜
